#!/bin/bash
yum update

# Install python
yum -y install python3-3.7.6

# Install pip
yum -y install python3-pip-9.0.3
pip3 install -Iv --upgrade pip==20.2.1

# Install supervisor
pip install supervisor==4.1.0

cd /home/ec2-user/python-flask-service

# Install python dev libraries for get_authorized_keys script
pip install -r requirements.txt

# Create python virtual environment
python3 -m venv environment

#Activate the virtual environment
source environment/bin/activate

# Install python dev libraries for virtual environment
pip install -r requirements.txt

mkdir downloads
cd downloads
pip install opencv-python
sudo yum install autoconf aclocal automake 
sudo yum install libtool 
sudo yum install libjpeg-devel libpng-devel libtiff-devel zlib-devel
wget http://www.leptonica.org/source/leptonica-1.72.tar.gz 
tar -zxvf leptonica-1.72.tar.gz 
cd leptonica-1.72 
./configure 
make 
sudo make install 
cd ..
tar -zxvf 3.04.00.tar.gz 
cd tesseract-3.04.00/ 
./autogen.sh 
./configure 
make
sudo make install 
sudo ldconfig
cd /usr/local/share/tessdata
sudo wget https://github.com/tesseract-ocr/tessdata/tree/3.04.00/eng.traineddata
sudo wget hhttp://tesseract-ocr.googlecode.com/files/tesseract-ocr-3.01.osd.tar.gz 
sudo tar xvf tesseract-ocr-3.01.osd.tar.gz 
sudo mv tesseract-ocr/tessdata/* . 
sudo rm tesseract-ocr-3.01.osd.tar.gz 
nano ~/.bash_profile # Copy this line to the end: export TESSDATA_PREFIX=/usr/local/share/ # Verify: tesseract --list-langs
pip install pytesseract
python setup.py install
